### ISSUE TITLE
Stuck at "Loading driver at 0x0007DCB0000 EntryPoint=0x0007DC22ED bootmgfw.efi"

### ISSUE THREAD

**Issue by leandrofriedrich** [rickliu2000/Lumia930Pkg#5]
Hello! I finally managed to compile this and it boots(kinda)!
![IMG_0092](https://user-images.githubusercontent.com/58913672/129232869-9a1685a0-99d8-41a4-ad6e-25e6841f8a67.JPG)
![IMG_0093](https://user-images.githubusercontent.com/58913672/129232879-a16e6acb-8c20-4f20-af12-6cb39281bcde.JPG)
As you can see i am always stuck at "Loading driver at 0x0007DCB0000 EntryPoint=0x0007DC22ED bootmgfw.efi" and no buttons work. Any ideas?

**Comment by leandrofriedrich** [comment]
wait it doesnt like windows xD

**Comment by qaz6750** [comment]
I want to ask you how to compile this project. I also have a problem at present
